name: Workflow test
on: [push]
jobs:
  Test-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
      - name: Check python version
        run: python --version

      - name: Install Pylint
        run: |
          pip install pylint
      - name: Run Pylint test
        run: python -m pylint ../../app.py

