name: Workflow test
on: [push]
jobs:
  Test-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check Python Version
      - uses: actions/setup-python@v4
      - run: python --version
      - uses: actions/setup-python@v4
      - name: Test app.py
      - run: python -m pylint app.py